---
- name: Configuration du serveur icingamaster
  hosts: icingamaster
  become: True
  vars:
    # Variables pour icinga2
    tomcat_major_version: 8

  roles:
    - icingaweb2
    - geerlingguy.postgresql
  
