---
- name: Configuration du serveur icingamaster
  hosts: icingamaster
  become: True
  vars:
    icinga2_ido_conf: /etc/icinga2/features-available/ido-pgsql.conf
    icinga2_bdd_util: icinga2
    icinga2_nom_bdd: icinga2
    icinga2_mdp_bdd: iHNeVuPpj5x2
    icinga2_serveur_bdd: localhost

  roles:
    - icinga2bdd
    - icinga2

  
