---
# tasks file for icinga2bdd

#- name: Installation des paquets pour postgresql
#  apt:
#    pkg={{ item }}
#    update_cache=yes
#    cache_valid_time=3600
#  with_items:
#    - postgresql
#
#- name: Activation de postgresql au demarrage du serveur
#  service:
#    name=postgresql
#    enabled=yes
#
#- name: Demarrage du service Postgres
#  service:
#    name=postgresql
#    state=started

- name: Ajout de la clef pour le depot pgdg
  apt_key:
    id=ACCC4CF8
    url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Ajout du depot pgdg
  apt_repository:
    repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
    filename='postgresql'

- name: Installation de postgresql
  apt:
    pkg={{item}}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - libpq-dev
    - postgresql-client
    - postgresql-contrib
    - postgresql
    - python-psycopg2 # requis par Ansible pour les modules postgresql

- name: Déploiement du fichier de configuration des utilisateurs
  template:
    src=templates/pg_hba.conf.j2
    dest={{ pg_hba_conf_file }}
    backup=no
  notify: restart postgresql

- name: Création de l utilisateur postgresql pour icinga2
  postgresql_user:
    name={{ icinga2_bdd_util }}
    password={{ icinga2_mdp_bdd }}
    encrypted=yes
    role_attr_flags=CREATEDB,NOSUPERUSER
    state=present
  become: true
  become_user: postgres

- name: Création de l utilisateur postgresql pour icingaweb2
  postgresql_user:
    name={{ icingaweb2_bdd_util }}
    password={{ icingaweb2_mdp_bdd }}
    encrypted=yes
    role_attr_flags=CREATEDB,NOSUPERUSER
    state=present
  become: true
  become_user: postgres

- name: Creation de la base icinga2
  postgresql_db:
    name={{ icinga2_nom_bdd }}
    encoding='UTF-8'
    owner={{ icinga2_bdd_util }}
  become: true
  become_user: postgres

- name: Creation de la base pour icingaweb2
  postgresql_db:
    name={{ icingaweb2_nom_bdd }}
    encoding='UTF-8'
    owner={{ icingaweb2_bdd_util }}
  become: true
  become_user: postgres


