---
# tasks file for icingaweb2

- name: Icinga Web2 Installation finished (Debian)
  debug: msg="Now generate a token with 'icingacli setup token create' and go at http://IP//icingaweb2/setup to continue the installation"
  tags: icinga2-ansible-web2-ui-install
