---
# tasks file for icingaweb2
- name: Installation des paquets pour icingaweb2
  apt:
    pkg={{item}}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - apache2
    - php5
    - php5-cli
    - php-pear
    - php5-xmlrpc
    - php5-xsl
    - php-soap
    - php5-gd
    - php5-ldap
    - php5-pgsql
    # Dependances Imagick et INTL
    - php5-intl
    - php5-imagick
    # icingaweb2
    - icingaweb2

- name: Copie du fichier de configuration de PHP php.ini (Ajout de la timezone Europe/Paris)
  template:
    src=templates/php.ini.j2
    dest={{ php_ini_dest }}
    backup=no
  notify: restart apache2

- name: Génération du token
  shell: icingacli setup token create
  register: icinga2_token

- name: Affichage du token
  debug: var=icinga2_token.stdout_lines

- name: Icinga Web2 Installation finished (Debian)
  debug: msg="Utiliser le token généré ci-dessus puis aller l'adresse suivante pour finir l'installation http://{{ ansible_default_ipv4.address }}/icingaweb2/setup"

