---
# tasks file for icinga2
- name: Ajout de la clef du depot debmon pour icinga2
  apt_key:
    url=http://debmon.org/debmon/repo.key
    state=present

- name: Ajout du depot debmon pour icinga2
  apt_repository:
    repo='deb http://debmon.org/debmon debmon-{{ansible_distribution_release}} main'
    state=present
    filename='icinga2'

- name: Ajout du depot debian backport (contient des dependances requises pour icinga2)
  apt_repository:
    repo='deb http://httpredir.debian.org/debian {{ansible_distribution_release}}-backports main'
    state=present
    filename='icinga2'

- name: Installation des paquets icinga2
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - icinga2
    - icinga2-ido-pgsql

- name: Copie du fichier de configuration de icinga2-ido-pgsql
  template:
    src=templates/ido-pgsql.j2
    dest={{ icinga2_ido_conf }}
    backup=no

- name: Activation des feature ido-pgsql et command
  shell: icinga2 feature enable command ido-pgsql
  notify: restart icinga2


